### ISSUE TITLE
[feature request] Set global download location

### ISSUE THREAD

**Issue by 77-77SP** [FunkyMuse/SubHub#10]
It would be awesome if there was an ability to set a download location for all subtitle downloads instead of having to select location every time.

Thank you for this amazing app.

**Comment by FunkyMuse** [comment]
sorry, the development of this app is postponed because i've no idea what will happen with OpenSubtitle's new api

**Comment by 77-77SP** [comment]
Thank you for the response. Have a wonderful day.
