### ISSUE TITLE
Information about how the App works

### ISSUE THREAD

**Issue by donenoyes** [FunkyMuse/SubHub#4]
Where are the subtitles fetched from? I see the retrofit library being used but I don't see `baseurl`

Can you point out in the code where the network request is made and subtitles are fetched from?

It would be really cool if you could share the details on the how the app works and its flow.

**Comment by FunkyMuse** [comment]
The app fetches details from open subtitles

**Comment by donenoyes** [comment]
@FunkyMuse It looks like you are using a library: 'com.github.FunkyMuse.Open-subtitles:opensubshiltsealed:1.0.1'

Is it opensource or if possible can you opensource it?
