### ISSUE TITLE
Manual search doesn't work.

### ISSUE THREAD

**Issue by The-BigSleep** [FunkyMuse/SubHub#5]
I've tested the app with multiple movie titles and always get the same response. 

I'm trying  English with a specified subhub folder within my downloads folder. 

I've also used opensubtitles to find the subtitles on my web browser. So it's not that the subtitles are unavailable. 

![Screenshot_20210811-230522_Subhub](https://user-images.githubusercontent.com/85153739/129132213-034e05b6-b383-4fbb-8d36-2f3896922ee5.jpg)

**Comment by FunkyMuse** [comment]
![Screenshot_20210812-081445](https://user-images.githubusercontent.com/25645122/129147077-42c8d56c-ee8d-4d9d-8b8d-c063f5a06ee6.png)

**Comment by The-BigSleep** [comment]
This doesn't actually solve my problem through :/
