### ISSUE TITLE
Can't pick download folder

### ISSUE THREAD

**Issue by fungorge** [FunkyMuse/SubHub#6]
when i tap on manual search, can't choose download folder, steps by picture:

tap on "download location folder":
![Screenshot_2021-08-31-10-59-16](https://user-images.githubusercontent.com/89831939/131454694-370b8b6b-16a6-470f-94aa-d5b2796a290f.png)

this menu opens with no folders in it:
![Screenshot_2021-08-31-10-59-34](https://user-images.githubusercontent.com/89831939/131455021-dc910f30-bede-4510-a706-40fb017a53bc.png)

when i choose "recent" (the only option):
![Screenshot_2021-08-31-10-59-46](https://user-images.githubusercontent.com/89831939/131455138-8a4ef255-c375-4675-bacd-6035d8a2125b.png)

without choosing downoad location, search doesn't start to work.

Android version: 5.1
Subhub version: 1.0.0
downloaded from: f-droid

**Comment by FunkyMuse** [comment]
Android 5.1 support would be dropped soon

Android 7.0 onwards

**Comment by fungorge** [comment]
Kinda seems not a solution :(

**Comment by FunkyMuse** [comment]
Android 5.X is 7 years old, soon 8, time to move on.
